# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function that triggers on an SNS topic publication when a new review is created

Resources:
    BuildMatchStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: build-match-stats.default
            Runtime: nodejs8.10
            Timeout: 360
            Tracing: Active
            CodeUri: ./dist/build-match-stats
            MemorySize: 512
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
                - AmazonSNSReadOnlyAccess
            Events:
                ReviewPublishedSnsTopic:
                    Type: SNS
                    Properties:
                        Topic: arn:aws:sns:us-west-2:478062583808:review-published
